artifact_location: /Workspace/Repos/labuser104917-3007326@vocareum.com/dscc202-402-spring2024/final_project/uri_to_your_mlflow_server/0
creation_time: 1715359972001
experiment_id: '0'
last_update_time: 1715359972001
lifecycle_stage: active
name: Default
