artifact_uri: /Workspace/Repos/labuser104917-3007326@vocareum.com/dscc202-402-spring2024/final_project/uri_to_your_mlflow_server/719837877407572980/f8c1ccf26ef54ac2b11fff0fadb1a0b3/artifacts
end_time: 1715472148532
entry_point_name: ''
experiment_id: '719837877407572980'
lifecycle_stage: active
run_id: f8c1ccf26ef54ac2b11fff0fadb1a0b3
run_name: marvelous-fly-153
run_uuid: f8c1ccf26ef54ac2b11fff0fadb1a0b3
source_name: ''
source_type: 4
source_version: ''
start_time: 1715472130653
status: 3
tags: []
user_id: root
